---
title: "Data Viz with R - Shiny"
author: "Yu-Zhen Tu<br>Data engineer at <a href=\"https://www.health2sync.com/tw/\">Health2Sync</a><br>Community Mentor of JHU \"R programming\" on Coursera"
date: "September X, 2018"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## What is Shiny?

- An R package that builds interactive web apps directly from R
- Can be presented by:
    - standalone apps on a webpage (compatible with mobile platforms)
    - [R Markdown](http://rmarkdown.rstudio.com/) documents
    - [Dashboards](http://rstudio.github.io/shinydashboard/)
- Can be extended with:
    - [CSS themes](http://rstudio.github.io/shinythemes/)
    - [htmlwidgets](http://www.htmlwidgets.org/)
    - JavaScript [actions](https://github.com/daattali/shinyjs/blob/master/README.md)

## Built-in demo

```{r, echo = TRUE, eval = FALSE}
library(shiny)

ui <- fluidPage(
   # Application title
   titlePanel("Old Faithful Geyser Data"),
   # Sidebar with a slider input for number of bins 
   sidebarLayout(
      sidebarPanel(
         ###<b>
         sliderInput("bins", "Number of bins:",
                     min = 1, max = 50, value = 30)
         ###</b>
      ),
      # Show a plot of the generated distribution
      mainPanel(
         ###<b>
         plotOutput("distPlot")
         ###</b>
      )
   )
)
```

## Built-in demo (cont.)

```{r, echo = TRUE, eval = FALSE}
server <- function(input, output) {
  # generate bins based on input$bins from ui.R
  # draw the histogram with the specified number of bins
  ###<b>
   output$distPlot <- renderPlot({
      x    <- faithful[, 2] 
      bins <- seq(min(x), max(x), length.out = input$bins + 1)
      hist(x, breaks = bins, col = 'darkgray', border = 'white')
   })
  ###</b>
}

# Run the application 
shinyApp(ui = ui, server = server)
```